Cart/urls.py
from django.urls import path
from Cart.views import cart_add,cart_detail,cart_remove

app_name = 'cart'

urlpatterns = [
    path('', cart_detail.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', cart_add.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', cart_remove.cart_remove, name='cart_remove'),
]

ENGR/urls.py
from django.contrib import admin
from django.urls import path,include
import Customer.views.Index
import Customer.views.Aftlogin
import Customer.views.Dologin
import Customer.views.Contact
import Customer.views.About
# from Store import views
from . import settings
from django.conf.urls.static import static
# from Cart import views




urlpatterns = [
    path('admin/', admin.site.urls),
    path('', Customer.views.Index.Index,name='index'),
    path('contact/', Customer.views.Contact.Contact,name='contact'),
    path('about/', Customer.views.About.About,name='about'),
    path('Customer/', include('Customer.urls') ),
    # path('dologin/', Customer.views.Dologin.dologin,name='Customer_dologin'),
    path('cart/', include('Cart.urls', namespace='cart')),
    path('orders/', include('Order.urls', namespace='orders')),
    path('payment/', include('Payment.urls', namespace='payment')),
    # path('cart/', views.cart_detail, name='cart_detail'),
    path('store/', include('Store.urls', namespace='store')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

Order/urls.py
from django.urls import path
from Order.views import order_create, order_show
app_name = 'orders'

urlpatterns = [
    path('create/', order_create.order_create, name='order_create'),
    path('order/', order_show.order_show, name='order_show'),

]

Store/urls.py
from django.urls import path
from Store.views import restaurant_list,restaurant_detail
from Store.views import product_detail
from Store.views import product_list
from Store.views import search
from Store.views import list

app_name = 'store'
urlpatterns = [
    path('<slug:slug>/<int:id>/', restaurant_detail.restaurat_detail, 
         name='restaurant_detail'),
    # path('<slug:category_slug>/', product_list.product_list,
    #      name='product_list_by_category'),
    path('<int:id>/<slug:slug>/', product_detail.product_detail,
         name='product_detail'),
    path('search',search.Search, name='store_dosearch'),
    path('list',list.List_all, name='list_restaurants'),
    path('', product_list.product_list, name='product_list'),

    
]

zENGR/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

Cart/models.py
from django.db import models

# Create your models here.

Cart/forms.py
from django import forms


PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 20)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(
                                choices=PRODUCT_QUANTITY_CHOICES,
                                coerce=int)
    override = forms.BooleanField(required=False,
                                  initial=False,
                                  widget=forms.HiddenInput)

Cart/views/cart_add.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from Store.models.Product import Product
from Cart.cart import Cart
from Cart.forms import CartAddProductForm
# import json


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    print("cart created")
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    # json_str = json.dumps(cart_add())
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=cd['quantity'],
                 override_quantity=cd['override'])
    return redirect('cart:cart_detail')

Cart/views/cart_detail.py
import json

from django.shortcuts import get_object_or_404, redirect, render
from django.views.decorators.http import require_POST

from Cart.cart import Cart
from Cart.forms import CartAddProductForm
from Customer.cuss import Cuss
from Store.models.Product import Product


def cart_detail(request):
    print("step1")
    cart = Cart(request)
    print("step2")
    update = None
    
    for item in cart:
        # item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'],
        #                                                            'override': True})
        update=CartAddProductForm(initial={'quantity': item['quantity'],
                                                    'override': True})                                          
    return render(request, 'templates/web/Cart/detail.html', {'cart':cart, 'up':update, 'cus':Cuss.cuss_id})

Cart/views/cart_remove.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from Store.models.Product import Product
from Cart.cart import Cart
from Cart.forms import CartAddProductForm


@require_POST
def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')

templates/web/cart/detail.html
{% extends "templates/base.html" %}
{% load static %}

{% block content %}
<div
  class="hero page-inner overlay"
  style="background-image: url('~/static/bootstrap5/images/hero_bg_1.jpg')"
  >
  <div class="container">
    <div class="row justify-content-center align-items-center">
      <div class="col-lg-9 text-center mt-5">
        <h1 class="heading" data-aos="fade-up">Your shopping cart</h1>

        <nav
          aria-label="breadcrumb"
          data-aos="fade-up"
          data-aos-delay="200"
          > 
          <ol class="breadcrumb text-center justify-content-center">
            <li class="breadcrumb-item"><a href="/../../">Home</a></li>
            <li
              class="breadcrumb-item active text-white-50"
              aria-current="page"
              >
              
            </li>
          </ol>
        </nav>
      </div>
    </div>
  </div>
</div>


<div class="section">
  <div class="container">
    <div class="row mb-5 align-items-center">
            <h1>Your shopping cart</h1>
        <table class="cart">
          <thead>
            <tr>
              <th>Image</th>
              <th>Product</th>
              <th>Quantity</th>
              <th>Remove</th>
              <th>Unit price</th>
              <th>Price</th>
            </tr>
          </thead>
          <tbody>
            {% for item in cart %}
              {% comment %} {% with product=item.product %} {% endcomment %}
                <tr>
                  <td>
                    <a href="{{ item.get_absolute_url }}">
                      <img class="img" style="max-width:25%;
                      max-height:25%;" src="{{ item.image_url }}">
                      {% comment %} {% else %}{% static "img/no_image.png" %}{% endif %}"> {% endcomment %}
                    </a>
                  </td>
                  <td>{{ item.name }}</td>
                  <td>
                    <form action="{% url "cart:cart_add" item.id %}" method="post">
                      {{ up.quantity }}
                      {{ up.override }}
                      <input type="submit" value="Update">
                      {% csrf_token %}
                    </form>
                  </td>
                  <td>
                    <form action="{% url "cart:cart_remove" item.id %}" method="post">
                      <input type="submit" value="Remove">
                      {% csrf_token %}
                    </form>
                  </td>
                  <td class="price">${{ item.price }}</td>
                  <td class="price">${{ item.total_price }}</td>
                </tr>
              {% comment %} {% endwith %} {% endcomment %}
            {% endfor %}
            <tr class="total">
              <td>Total</td>
              <td colspan="4"></td>
              <td class="num">${{ cart.get_total_price }}</td>
            </tr>
          </tbody>
        </table>
        <p class="text-right">
          <a href="{% url "store:product_list" %}" class="btn btn-primary">
            Continue shopping</a>
          <a href="{% url "orders:order_create" %}" class="btn btn-primary" style="float: right">
            Checkout         </a>
        </p>   
    </div>
  </div>
</div>

<script type="text/javascript" src="/static/bootstrap5/js/bootstrap.bundle.min.js"></script>
<script type="text/javascript" src="/static/bootstrap5/js/tiny-slider.js"></script>
<script type="text/javascript" src="/static/bootstrap5/js/aos.js"></script>
<script type="text/javascript" src="/static/bootstrap5/js/navbar.js"></script>
<script type="text/javascript" src="/static/bootstrap5/js/counter.js"></script>
<script type="text/javascript" src="/static/bootstrap5/js/custom.js"></script>  

  
{% endblock %}