Cart/urls.py
from django.urls import path
from Cart.views import cart_add,cart_detail,cart_remove

app_name = 'cart'

urlpatterns = [
    path('', cart_detail.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', cart_add.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', cart_remove.cart_remove, name='cart_remove'),
]

ENGR/urls.py
from django.contrib import admin
from django.urls import path,include
import Customer.views.Index
import Customer.views.Aftlogin
import Customer.views.Dologin
import Customer.views.Contact
import Customer.views.About
# from Store import views
from . import settings
from django.conf.urls.static import static
# from Cart import views




urlpatterns = [
    path('admin/', admin.site.urls),
    path('', Customer.views.Index.Index,name='index'),
    path('contact/', Customer.views.Contact.Contact,name='contact'),
    path('about/', Customer.views.About.About,name='about'),
    path('Customer/', include('Customer.urls') ),
    # path('dologin/', Customer.views.Dologin.dologin,name='Customer_dologin'),
    path('cart/', include('Cart.urls', namespace='cart')),
    path('orders/', include('Order.urls', namespace='orders')),
    path('payment/', include('Payment.urls', namespace='payment')),
    # path('cart/', views.cart_detail, name='cart_detail'),
    path('store/', include('Store.urls', namespace='store')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

Store/urls.py
from django.urls import path
from Store.views import restaurant_list,restaurant_detail
from Store.views import product_detail
from Store.views import product_list
from Store.views import search
from Store.views import list

app_name = 'store'
urlpatterns = [
    path('<slug:slug>/<int:id>/', restaurant_detail.restaurat_detail, 
         name='restaurant_detail'),
    # path('<slug:category_slug>/', product_list.product_list,
    #      name='product_list_by_category'),
    path('<int:id>/<slug:slug>/', product_detail.product_detail,
         name='product_detail'),
    path('search',search.Search, name='store_dosearch'),
    path('list',list.List_all, name='list_restaurants'),
    path('', product_list.product_list, name='product_list'),

    
]

zENGR/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

Store/models/Category.py
from django.db import models
from django.urls import reverse


class Category(models.Model):
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200,
                            unique=True)
    class Meta:
        ordering = ['name']
        indexes = [
            models.Index(fields=['name']),
        ]
        verbose_name = 'category'
        verbose_name_plural = 'categories'
    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('store:restaurant_list_by_category',
                       args=[self.slug])

Store/models/Product.py
from django.db import models
from django.urls import reverse
from Store.models.Restaurant import Restaurant


class Product(models.Model):
    restaurant = models.ForeignKey(Restaurant,
                                 related_name='products',
                                 on_delete=models.CASCADE)

    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200)
    image = models.ImageField(upload_to='products/%Y/%m/%d',
                              blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10,
                                decimal_places=2)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def toDict(self):
        return {'restaurant':self.restaurant,'name':self.name, 'slug':self.slug, 'image':self.image, 'description':self.description,'price':str(self.price), 'available':self.available,'created':self.created.strftime('%Y-%m-%d %H:%M:%S'),'updated':self.updated.strftime('%Y-%m-%d %H:%M:%S')} 

    
    class Meta:
        ordering = ['name']
        indexes = [
            models.Index(fields=['slug', 'id']),
            models.Index(fields=['name']),
            models.Index(fields=['-created']),
        ]
    def __str__(self):
        return self.name

    

    def get_absolute_url(self):
        return reverse('store:product_detail',
                       args=[self.id, self.slug])

Store/models/Restaurant.py
from django.db import models
from django.urls import reverse
from Store.models.Category import Category

class Restaurant(models.Model):
    category = models.ForeignKey(Category,
                                 related_name='restaurants',
                                 on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200)
    image = models.ImageField(upload_to='restaurant/%Y/%m/%d',
                              blank=True)
    description = models.TextField(blank=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    address = models.CharField(max_length=200,default='null')

    def toDict(self):
        return {'category':self.category,'name':self.name, 'slug':self.slug, 'image':self.image, 'description':self.description,'created':self.created.strftime('%Y-%m-%d %H:%M:%S'),'updated':self.updated.strftime('%Y-%m-%d %H:%M:%S'),'address':self.address} 
    
    class Meta:
        ordering = ['name']
        indexes = [
            models.Index(fields=['id', 'slug']),
            models.Index(fields=['name']),
            models.Index(fields=['-created']),
        ]
        verbose_name = 'restaurant'
        verbose_name_plural = 'restaurants'
    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('store:restaurant_detail',
                       args=[self.slug,self.id])

Store/views/list.py
from distutils.log import error
from re import L
from tkinter import END
from django.shortcuts import get_object_or_404, render
from Store.models.Category import Category
from Store.models.Product import Product
from Store.models.Restaurant import Restaurant
import MySQLdb
from Customer.cuss import Cuss


def List_all(request):
    list = Restaurant.objects.all()
   
    print(list)
    
    return render(request, 
                    'templates/web/Store/product/listall.html',
                   {'result':list,
                    'cus':Cuss.cuss_id})

Store/views/product_detail.py
from django.shortcuts import get_object_or_404, render
from Store.models.Category import Category
from Store.models.Product import Product
from Store.models.Restaurant import Restaurant
from Cart.forms import CartAddProductForm
from Customer.cuss import Cuss
# Create your views here.
def product_detail(request, id, slug):
    product = get_object_or_404(Product,
                                id=id,
                                slug=slug,
                                available=True)
    cart_product_form = CartAddProductForm()                               
    return render(request,
                  'templates/web/Store/product/detail.html',
                  {'product': product,
                   'cart_product_form': cart_product_form,
                   'cus': Cuss.cuss_id})

Store/views/product_list.py
from django.shortcuts import get_object_or_404, render
from Store.models.Category import Category
from Store.models.Product import Product
from Store.models.Restaurant import Restaurant
from Cart.forms import CartAddProductForm
from Customer.cuss import Cuss
# Create your views here.
def product_list(request, restaurant_slug=None):
    restaurant = None
    restaurants = Restaurant.objects.all()
    products = Product.objects.filter(available=True)
    if restaurant_slug:
        restaurant = get_object_or_404(Restaurant, 
                                     slug=restaurant_slug)
        products = products.filter(restaurant=restaurant)
    return render(request,
                  'templates/web/Store/product/list.html',
                  {'restaurant': restaurant,
                   'restaurants': restaurants,
                   'products': products,
                   'cus': Cuss.cuss_id})

Store/views/restaurant_detail.py
from django.shortcuts import get_object_or_404, render
from Store.models.Category import Category
from Store.models.Product import Product
from Store.models.Restaurant import Restaurant
from Cart.forms import CartAddProductForm
from Customer.cuss import Cuss
from django.urls import reverse
# Create your views here.
def restaurat_detail(request, id, slug):
    restaurant = get_object_or_404(Restaurant,
                                slug=slug,
                                id=id,
                                )
    product = Product.objects.filter(restaurant_id=id) 
    cart_product_form = CartAddProductForm() 
                        
    return render(request,
                  'templates/web/Store/product/restaurant.html',
                  {'restaurant': restaurant,
                   'product': product,
                   'cart_product_form': cart_product_form,
                   'cus':Cuss.cuss_id})

Store/views/restaurant_list.py
from django.shortcuts import get_object_or_404, render
from Store.models.Category import Category
from Store.models.Product import Product
from Store.models.Restaurant import Restaurant
from Cart.forms import CartAddProductForm
from Customer.cuss import Cuss

def restaurant_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    restaurants = Restaurant.objects.all()
    if category_slug:
        category = get_object_or_404(Category, 
                                     slug=category_slug)
        restaurants = restaurants.filter(category=category)

    return render(request,
                  'templates/web/Store/product/restaurant.html',
                  {'category': category,
                   'categories': categories,
                   'restaurants': restaurants,
                   'cus':Cuss.cuss_id})

Store/views/search.py
from errno import errorcode
from multiprocessing import context
import traceback
from Store.models.Category import Category
from Store.models.Product import Product
from Store.models.Restaurant import Restaurant
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse
from django.db.models import Q
from django.contrib import messages
from Store.views import restaurant_list
from Customer.cuss import Cuss



def Search(request):

    try:
        name = request.POST['search']
        print(name)
        Q_Product = Product.objects.filter(slug__icontains=name)
        print(Q_Product)
        Q_Restaurant = Restaurant.objects.filter(slug__icontains=name)
        print(Q_Restaurant)
              
        return render(request, 'templates/web/Store/result.html',
                                {'resultP':Q_Product,
                                'resultR':Q_Restaurant,
                                'cus': Cuss.cuss_id})
    except:
        messages.error(request,'food does not exist!')
        traceback.print_exc()
        return render(request, 'templates/web/re-log/index.html', {'cus': Cuss.cuss_id} )

templates/web/Store/product/detail.html
{% extends "templates/base.html" %}
{% load static%}
{% block content %}
<div
  class="hero page-inner overlay"
  style="background-image: url('images/hero_bg_1.jpg')"
  >
  <div class="container">
    <div class="row justify-content-center align-items-center">
      <div class="col-lg-9 text-center mt-5">
        <h1 class="heading" data-aos="fade-up">{{ product.name }}</h1>

        <nav
          aria-label="breadcrumb"
          data-aos="fade-up"
          data-aos-delay="200"
          > 
          <ol class="breadcrumb text-center justify-content-center">
            <li class="breadcrumb-item"><a href='/../'>Home</a></li>
            <li
              class="breadcrumb-item active text-white-50"
              aria-current="page"
              >
              {{ product.restaurant }}
            </li>
          </ol>
        </nav>
      </div>
    </div>
  </div>
</div>

<div class="section">
  <div class="container">
    <div class="row mb-5 align-items-center">
      <div class="property-item mb-30">
        <a href="product.get_absolute_url" class="img">
          <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}" alt="Image" class="img-fluid" />
        </a>
        <div class="property-content">
          <div class="price mb-2"><span>{{ product.restaurant }}</span></div>
          <div class="price mb-2"><span><a href="{{ product.get_absolute_url }}">
            {{ product.name }}
          </a></span></div>
          <div>
            <span class="d-block mb-2 text-black-50"
              > ${{ product.price }}</span
            >
          </div>
        </div>
        <form action="{% url "cart:cart_add" product.id %}" method="post">
          {{ cart_product_form }}
          {% csrf_token %}
          <input type="submit" value="Add to cart">
        </form>    
        {{ product.description|linebreaks }}
      </div>   
    </div>
  </div>
</div>

<script type="text/javascript" src="/static/bootstrap5/js/bootstrap.bundle.min.js"></script>
<script type="text/javascript" src="/static/bootstrap5/js/tiny-slider.js"></script>
<script type="text/javascript" src="/static/bootstrap5/js/aos.js"></script>
<script type="text/javascript" src="/static/bootstrap5/js/navbar.js"></script>
<script type="text/javascript" src="/static/bootstrap5/js/counter.js"></script>
<script type="text/javascript" src="/static/bootstrap5/js/custom.js"></script>  


{% endblock %}

templates/web/Store/product/list.html
{% extends "templates/base.html" %}
{% load static %}

{% block content %}
<div class="hero">
    <div class="hero-slide">
      <div
        class="img overlay"
        style="background-image: url('/static/bootstrap5/images/hero_bg_3.jpg')"
      ></div>
      {% comment %} <div
        class="img overlay"
        style="background-image: url('/static/bootstrap5/images/hero_bg_2.jpg')"
      ></div>
      <div
        class="img overlay"
        style="background-image: url('/static/bootstrap5/images/hero_bg_1.jpg')"
      ></div> {% endcomment %}
    </div>


  <div class="container">
    <div class="row justify-content-center align-items-center">
      <div class="col-lg-9 text-center">
        <h1 class="heading" data-aos="fade-up">
          Easiest way to find what to eat
        </h1>
        <form
          action="{% url 'store:store_dosearch' %}"
          method="post" 
          class="narrow-w form-search d-flex align-items-stretch mb-3"
          data-aos="fade-up"
          data-aos-delay="200"
        >{% csrf_token %}
          <input
            type="text"
            name="search"
            class="form-control px-4"
            placeholder="Enter food type or name or restaurants e.g. cafe"
          />
          <button type="submit" class="btn btn-primary">Search</button>
        </form>
      </div>
    </div>
  </div>
</div>

<div class="section">
  <div class="container">
    <div class="row mb-5 align-items-center">
      <div class="col-lg-6 text-center mx-auto">
        <h2 class="font-weight-bold text-primary heading">
          Products
        </h2>
      </div>
    </div>
  </div>
</div>
<div class="section section-properties">
<div class="container">
  <div class="row">
    {% for product in products %}
      <div class="col-xs-12 col-sm-6 col-md-6 col-lg-4">
        <div class="property-item mb-30">
          <a href="product.get_absolute_url" class="img">
            <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}" alt="Image" class="img-fluid" />
          </a>
          <div class="property-content">
            <div class="price mb-2"><span><a href="{{ product.get_absolute_url }}">{{ product.name }}</a></span></div>
            <div>
              <span class="d-block mb-2 text-black-50"
                > ${{ product.price }}</span
              >
            </div>
          </div>
        </div>
      </div>
    {%endfor%}
  </div>
</div>
  


<script type="text/javascript" src="/static/bootstrap5/js/bootstrap.bundle.min.js"></script>
<script type="text/javascript" src="/static/bootstrap5/js/tiny-slider.js"></script>
<script type="text/javascript" src="/static/bootstrap5/js/aos.js"></script>
<script type="text/javascript" src="/static/bootstrap5/js/navbar.js"></script>
<script type="text/javascript" src="/static/bootstrap5/js/counter.js"></script>
<script type="text/javascript" src="/static/bootstrap5/js/custom.js"></script>  

{% endblock %}

templates/web/Store/product/listall.html
{% extends "templates/base.html" %}
<!DOCTYPE html>
{% block content %}



<div class="hero">
  <div class="hero-slide">
    <div
      class="img overlay"
      style="background-image: url('/static/bootstrap5/images/hero_bg_3.jpg')"
    ></div>
    <div
      class="img overlay"
      style="background-image: url('/static/bootstrap5/images/hero_bg_2.jpg')"
    ></div>
    <div
      class="img overlay"
      style="background-image: url('/static/bootstrap5/images/hero_bg_1.jpg')"
    ></div>
  </div>

  <div class="container">
    <div class="row justify-content-center align-items-center">
      <div class="col-lg-9 text-center">
        <h1 class="heading" data-aos="fade-up">
          Easiest way to find what to eat
        </h1>
        <form
          action="{% url 'store:store_dosearch' %}"
          method="post" 
          class="narrow-w form-search d-flex align-items-stretch mb-3"
          data-aos="fade-up"
          data-aos-delay="200"
        >{% csrf_token %}
          <input
            type="text"
            name="search"
            class="form-control px-4"
            placeholder="Enter food type or name or restaurants e.g. cafe"
          />
          <button type="submit" class="btn btn-primary">Search</button>
        </form>
      </div>
    </div>
  </div>
</div>

<div class="section">
  <div class="container">
    <div class="row mb-5 align-items-center">
      <div class="col-lg-6 text-center mx-auto">
        <h2 class="font-weight-bold text-primary heading">
          Restaurants
        </h2>
      </div>
    </div>
  </div>
</div>
<div class="section section-properties">
<div class="container">
  <div class="row">
  {%for l in result%}
      <div class="col-xs-12 col-sm-6 col-md-6 col-lg-4">
        <div class="property-item mb-30">
          <a class="img">
            <img src="{{l.image.url}}"{{l.image}} alt="Image" class="img-fluid" />
          </a>

          <div class="property-content">
            <div class="price mb-2"><span>{{l.name}}</span></div>
            <div>
              <span class="d-block mb-2 text-black-50"
                >{{l.description}}</span
              >
              <span class="city d-block mb-3">{{l.address}}</span>

              <div class="specs d-flex mb-4">
                <span class="d-block d-flex align-items-center me-3">
                  {% comment %} <span class="icon-bed me-2"></span> {% endcomment %}
                  {% comment %} <span class="caption">{{l.get_absolute_url}}</span> {% endcomment %}
                </span>
                <span class="d-block d-flex align-items-center">
                  {% comment %} <span class="icon-bath me-2"></span> {% endcomment %}
                  {% comment %} <span class="caption">2 baths</span> {% endcomment %}
                </span>
              </div>
              
              <a
                href="{{l.get_absolute_url}}"
                class="btn btn-primary py-2 px-3"
                >See details</a
              >
            </div>
          </div>
        </div>
      
      </div>
    {% comment %} <div class="row align-items-center py-5">
      <div class="col-lg-3">Pagination (1 of 10)</div>
      <div class="col-lg-6 text-center">
        <div class="custom-pagination">
          <a href="#">1</a>
          <a href="#" class="active">2</a>
          <a href="#">3</a>
          <a href="#">4</a>
          <a href="#">5</a>
        </div>
      </div> {% endcomment %}

  {%endfor%}
  </div>
</div>

</div>



<!-- /.site-footer -->

<!-- Preloader -->
{% comment %} <div id="overlayer"></div>
<div class="loader">
  <div class="spinner-border" role="status">
    <span class="visually-hidden">Loading...</span>
  </div>
</div> {% endcomment %}

<script type="text/javascript" src="/static/bootstrap5/js/bootstrap.bundle.min.js"></script>
<script type="text/javascript" src="/static/bootstrap5/js/tiny-slider.js"></script>
<script type="text/javascript" src="/static/bootstrap5/js/aos.js"></script>
<script type="text/javascript" src="/static/bootstrap5/js/navbar.js"></script>
<script type="text/javascript" src="/static/bootstrap5/js/counter.js"></script>
<script type="text/javascript" src="/static/bootstrap5/js/custom.js"></script> 




{% endblock %}

templates/web/Store/product/restaurant.html
{% extends "templates/base.html" %}
<!DOCTYPE html>
{% block content %}

<div class="hero">
  <div class="container">
    <div class="row justify-content-center align-items-center">
      <div class="col-lg-9 text-center">
        <h1 class="heading" data-aos="fade-up">
          Easiest way to find what to eat
        </h1>
        <form
          action="{% url 'store:store_dosearch' %}"
          method="post" 
          class="narrow-w form-search d-flex align-items-stretch mb-3"
          data-aos="fade-up"
          data-aos-delay="200"
        >{% csrf_token %}
          <input
            type="text"
            name="search"
            class="form-control px-4"
            placeholder="Enter food type or name or restaurants e.g. cafe"
          />
          <button type="submit" class="btn btn-primary">Search</button>
        </form>
      </div>
    </div>
  </div>
</div>

<div class="section">
  <div class="container">
    <div class="row mb-5 align-items-center">
      <div class="col-lg-6 text-center mx-auto">
        <h2 class="font-weight-bold text-primary heading">
          {{restaurant.name}}
          <p>{{restaurant.address}}</p>
          <p>{{restaurant.description}}</p>
        </h2>
      </div>
    </div>
  </div>
</div>

<div class="section">
  <div class="container">
    <div class="row">
      {% for p in product %}
      <div class="col-xs-12 col-sm-6 col-md-6 col-lg-4">
        <div class="property-item mb-30">
          <a href="{{p.get_absolute_url}}" class="img">
            <img src=" {{ p.image.url }} " alt="Image" class="img-fluid" />
          </a>
          <div class="property-content">
            <div class="price mb-2"><span>{{ p.restaurant }}</span></div>
            <div class="price mb-2"><span><a href="{{ p.get_absolute_url }}">
              {{ p.name }}
            </a></span></div>
            <div>
              <span class="d-block mb-2 text-black-50"
                > ${{ p.price }}</span
              >
            </div>
          </div>
          <form action="{% url "cart:cart_add" p.id %}" method="post">
            {{ cart_product_form }}
            {% csrf_token %}
            <input type="submit" value="Add to cart">
          </form>    
          {{ p.description|linebreaks }}
        </div>   
      </div>
      {% endfor %}
    </div>
  </div>
</div>


<script type="text/javascript" src="/static/bootstrap5/js/bootstrap.bundle.min.js"></script>
<script type="text/javascript" src="/static/bootstrap5/js/tiny-slider.js"></script>
<script type="text/javascript" src="/static/bootstrap5/js/aos.js"></script>
<script type="text/javascript" src="/static/bootstrap5/js/navbar.js"></script>
<script type="text/javascript" src="/static/bootstrap5/js/counter.js"></script>
<script type="text/javascript" src="/static/bootstrap5/js/custom.js"></script>

{% endblock %}