Cart/urls.py
from django.urls import path
from Cart.views import cart_add,cart_detail,cart_remove

app_name = 'cart'

urlpatterns = [
    path('', cart_detail.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', cart_add.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', cart_remove.cart_remove, name='cart_remove'),
]

ENGR/urls.py
from django.contrib import admin
from django.urls import path,include
import Customer.views.Index
import Customer.views.Aftlogin
import Customer.views.Dologin
import Customer.views.Contact
import Customer.views.About
# from Store import views
from . import settings
from django.conf.urls.static import static
# from Cart import views




urlpatterns = [
    path('admin/', admin.site.urls),
    path('', Customer.views.Index.Index,name='index'),
    path('contact/', Customer.views.Contact.Contact,name='contact'),
    path('about/', Customer.views.About.About,name='about'),
    path('Customer/', include('Customer.urls') ),
    # path('dologin/', Customer.views.Dologin.dologin,name='Customer_dologin'),
    path('cart/', include('Cart.urls', namespace='cart')),
    path('orders/', include('Order.urls', namespace='orders')),
    path('payment/', include('Payment.urls', namespace='payment')),
    # path('cart/', views.cart_detail, name='cart_detail'),
    path('store/', include('Store.urls', namespace='store')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

payment/urls.py
from django.urls import path
from . import views
app_name = 'payment'
urlpatterns = [
    path('process/', views.payment_process, name='process'),
    path('completed/', views.payment_completed, name='completed'),
    path('canceled/', views.payment_canceled, name='canceled'),
]

zENGR/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

Customer/models/payment.py
from django.db import models
from datetime import datetime

class Payment(models.Model):
    cardnumber = models.CharField(max_length=100)    #cardnumber
    secureNo = models.CharField(max_length= 5)       #security number
    # customerID = models.IntegerField()                 #to pare with the id in class customer
    create_at = models.DateTimeField(default=datetime.now)    #creat time
    update_at = models.DateTimeField(default=datetime.now)    #update time


    def toDict(self):
        return {'cardnumber':self.cardnumber,'secureNo':self.secureNo,'customerID':self.customerID,'create_at':self.create_at.strftime('%Y-%m-%d %H:%M:%S'),'update_at':self.update_at.strftime('%Y-%m-%d %H:%M:%S'),} 
    class Meta:

        db_table = "payment"  # change the name of the table

Customer/views/Payment.py
from datetime import datetime
from django.shortcuts import render
from django.shortcuts import render
from Customer.models.payment import Payment

def Payment(request):
    try:
        ob=Payment()
        ob.cardnumber = request.POST.get('username')
        ob.secureNo = request.POST.get('password')
        ob.create_at = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        ob.update_at = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        ob.save()

        context = {'info':"Successfully Add!!"}
        return render(request,'web\ re-log\ register.html',)

    except Exception as err:
        print(err)
        context = {'info':"Add Failed!!"}   
        return render(request,'web\ re-log\ register.html',) 

payment/views.py
from decimal import Decimal
import stripe
from ENGR import settings
from django.shortcuts import render, redirect,\
                             get_object_or_404
from Order.models import Order
from django.urls import  reverse
from Customer.cuss import Cuss

# create the Stripe instance

stripe.api_key = settings.STRIPE_SECRET_KEY
stripe.api_version = settings.STRIPE_API_VERSION

def payment_process(request):
    order_id = request.session.get('order_id', None)
    order = get_object_or_404(Order, id=order_id)
    if request.method == 'POST':
        success_url = request.build_absolute_uri(
                        reverse('payment:completed'))
        cancel_url = request.build_absolute_uri(
                        reverse('payment:canceled'))
        # Stripe checkout session data
        session_data = {
            'mode': 'payment',
            'client_reference_id': order.id,
            'success_url': success_url,
            'cancel_url': cancel_url,
            'line_items': []
        }
        # add order items to the Stripe checkout session
        for item in order.items.all():
            session_data['line_items'].append({
                'price_data': {
                    'unit_amount': int(item.price * Decimal('100')),
                    'currency': 'usd',
                    'product_data': {
                        'name': item.product.name,
                    },
                },
                'quantity': item.quantity,
            })
        # create Stripe checkout session
        session = stripe.checkout.Session.create(**session_data)
        # redirect to Stripe payment form
        return redirect(session.url, code=303)
    else:
        return render(request, 'templates/web/payment/process.html',locals())


def payment_completed(request):
    cus=Cuss.cuss_id
    return render(request, 'templates/web/payment/completed.html',{'cus':cus})
def payment_canceled(request):
    cus=Cuss.cuss_id
    return render(request, 'templates/web/payment/canceled.html',{'cus':cus})

templates/web/payment/canceled.html
{% extends "templates/base.html" %}
{% block title %}Payment canceled{% endblock %}
{% block content %}
<div
  class="hero page-inner overlay"
  style="background-image: url('~/static/bootstrap5/images/hero_bg_1.jpg')"
  >
  <div class="container">
    <div class="row justify-content-center align-items-center">
      <div class="col-lg-9 text-center mt-5">
        <h1 class="heading" data-aos="fade-up">Sorry</h1>

        <h1 class="heading" data-aos="fade-up" >Your payment has not been processed</h1>
        <h1>There was a problem processing your payment.</h1>
        <nav
          aria-label="breadcrumb"
          data-aos="fade-up"
          data-aos-delay="200"
          > 
          <ol class="breadcrumb text-center justify-content-center">
            <li class="breadcrumb-item"><a href="/../../">Home</a></li>
            <li
              class="breadcrumb-item active text-white-50"
              aria-current="page"
              >
              
            </li>
          </ol>
        </nav>
      </div>
    </div>
  </div>
</div>

{% endblock %}

templates/web/payment/completed.html
{% extends "templates/base.html" %}
{% block title %}Payment successful{% endblock %}
{% block content %}
<div
  class="hero page-inner overlay"
  style="background-image: url('~/static/bootstrap5/images/hero_bg_1.jpg')"
  >
  <div class="container">
    <div class="row justify-content-center align-items-center">
      <div class="col-lg-9 text-center mt-5">
        <h1 class="heading" data-aos="fade-up">Thank you!</h1>

        <h1 class="heading" data-aos="fade-up">Your payment was successful</h1>
        <h1 class="heading" data-aos="fade-up">Your payment has been processed successfully.</h1>
        <nav
          aria-label="breadcrumb"
          data-aos="fade-up"
          data-aos-delay="200"
          > 
          <ol class="breadcrumb text-center justify-content-center">
            <li class="breadcrumb-item"><a href="/../../">Home</a></li>
            <li
              class="breadcrumb-item active text-white-50"
              aria-current="page"
              >
              
            </li>
          </ol>
        </nav>
      </div>
    </div>
  </div>
</div>

{% endblock %}

templates/web/payment/done.html
{% extends "shop/base.html" %}
{% block title %}Payment successful{% endblock %}
{% block content %}
  <h1>Your payment was successful</h1>
  <p>Your payment has been processed successfully.</p>
{% endblock %}

templates/web/payment/process.html
{% extends "templates/base.html" %}
{% load static %}
{% block title %}Pay your order{% endblock %}
{% block content %}
<div
  class="hero page-inner overlay"
  style="background-image: url('/../static/bootstrap5/images/hero_bg_1.jpg')"
  >
  <div class="container">
    <div class="row justify-content-center align-items-center">
      <div class="col-lg-9 text-center mt-5">
        <h1 class="heading" data-aos="fade-up">Order summary</h1>

        <nav
          aria-label="breadcrumb"
          data-aos="fade-up"
          data-aos-delay="200"
          > 
          <ol class="breadcrumb text-center justify-content-center">
            <li class="breadcrumb-item"><a href="/../">Home</a></li>
            <li
            class="breadcrumb-item active text-white-50"
            aria-current="page"
          >
            Order Sum
          </li>
          </ol>
        </nav>
      </div>
    </div>
  </div>
</div>






<div class="section">
  <div class="container">
    <div class="order-info">          
      <table class="cart">
        <thead>
          <tr>
            <th>Image</th>
            <th>Product</th>
            <th>Quantity</th>
            <th>Unit price</th>
            <th>Price</th>
          </tr>
        </thead>
        <tbody>
      {% for item in order.items.all %}
        <tr class="row{% cycle "1" "2" %}">
          <td>
            <img src="{% if item.product.image %}{{ item.product.image.url }} 
            {% else %}{% static "img/no_image.png" %}{% endif %}" style="max-width:25%;
            max-height:25%;">
          </td>
          <td>{{ item.product.name }}</td>
          <td style="middle">{{ item.quantity }}</td>
          <td>${{ item.price }}</td>
          <td>${{ item.get_cost }}</td>
        </tr>
      {% endfor %}
      <tr class="total">
        <td colspan="4">Total</td>
        <td class="num">${{ order.get_total_cost }}</td>
      </tr>
    </tbody>
  </table>
  <form action="{% url "payment:process" %}" method="post">
    <input type="submit" value="Pay now" class="btn btn-primary" style="float: right">
    {% csrf_token %}
  </form>
  </div>
</div>


      
{% endblock %}